language: python

matrix:
  include:
    - os: osx
      language: generic

install:
  - wget https://www.dropbox.com/s/zmkkab2xfgjy3iq/portable-python-384-with-ssl-disable-shared-static-libs.zip
  - unzip portable-python-384-with-ssl-disable-shared-static-libs
  - whereis openssl
  - sudo apt-get remove --auto-remove openssl

script:
  - portable-python-384-with-ssl-disable-shared-static-libs/bin/python3 -m pip install --upgrade pip
  - portable-python-384-with-ssl-disable-shared-static-libs/bin/python3 -m venv penv
  - penv/bin/pip install platformio
  - penv/bin/platformio boards

notifications:
  email: false
