name: Run

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python ${{ matrix.python-version }}
        run: |
          wget https://www.dropbox.com/s/zmkkab2xfgjy3iq/portable-python-384-with-ssl-disable-shared-static-libs.zip
          unzip portable-python-384-with-ssl-disable-shared-static-libs
          whereis openssl
          brew uninstall --ignore-dependencies openssl
          whereis openssl
      - name: Install dependencies
        run: |
          portable-python-384-with-ssl-disable-shared-static-libs/bin/python3 -m pip install --upgrade pip
          portable-python-384-with-ssl-disable-shared-static-libs/bin/python3 -m venv penv
          penv/bin/pip install platformio
          penv/bin/platformio boards
